<?php
namespace ResourceCatalog\Model;

interface IResourceCatalog extends IResourceCatalogTypeName, IResourceCatalogTypeIdentify, IResourceCatalogTypeEnName, IResourceCatalogTypeDoublePublicity, IResourceCatalogTypeRedBlackList, IResourceCatalogIsConfirm
{
    const TYPE = array(
         'NULL' => 0,
        'XBXZCF' => 1,
        'XBXZXK' => 2,
        'SXBZXRMD' => 3,
        'FRXX' => 4,
        'QIYEJBXX' => 5,
        'GTGSHXX' => 6,
        'CMQYSBXX' => 7,
        'YPLSQYXX' => 8,
        'JGRYXX' => 9,
        'SXQYHMD' =>10,
        'SPYPTSJBJLGR' => 11,
        'SPYPTSJBJLDW' => 12,
        'HNMPCPXX' => 13,
        'QYYCMLXX' => 14,
        'QYZXXX' => 15,
        'QYDXXX' => 16,
        'CCJCJGXX' => 17,
        'JGJCDXZJL' => 18,
        'YSCRJZJJJZGRDXX' => 19,
        'JDCWFXX' => 20,
        'JSZGXX' => 21,
        'SJYXXS' => 22,
        'JYJGXINXI' => 23,
        'GRRYXXJYJ' => 24,
        'JGRYXXSJYJ' => 25,
        'ESCJDPGJGHZZS' => 26,
        'ZYJNZSXX' => 27,
        'YLBXXX' => 28,
        'YZTQSBXXHMD' => 29,
        'SYBXXX' => 30,
        'SBQYXX' => 31,
        'GZRYXX' => 32,
        'YZTQNMGGZHMD' => 33,
        'SLYSXKZXX' => 34,
        'GRRYXXJTJ' => 35,
        'QYGSZXXX' => 36,
        'AJNSRXX' => 37,
        'ZDSSWFAJXX' => 38,
        'QYDSXZCFXX' => 39,
        'SHZZNJXX' => 40,
        'GRRYXXMZJ' => 41,
        'MBFQYML' => 42,
        'SHTTDJXX' => 43,
        'SFJDJGCYRYZGXX' => 44,
        'SFJDJGDJXX' => 45,
        'GZJGJBXX' => 46,
        'GZYXX' => 47,
        'JCFLFWSXX' => 48,
        'JCFLFWGZZJBXX' => 49,
        'LSSWSXX' => 50,
        'LSZYZGZXX' => 51,
        'JGRYXXSSFJ' => 52,
        'SJQYJSZXRDXX' => 53,
        'ZFCGDLJGXX' => 54,
        'SLGCZBXX' => 55,
        'GJJLTQYRZXX' => 56,
        'DTJXJGRXX' => 57,
        'TJDCDXML' => 58,
        'HNSZLJDW' => 59,
        'XSPJXX' => 60,
        'SXBZXJGXX' => 61,
        'SJJXMXX' => 62,
        'XZXKQYXX' => 63,
        'QSLHXJJTJL' => 64,
        'SPFYSXK' => 65,
        'FDCKFQYZZXX' => 66,
        'JGRYXXSFGJ' => 67,
        'XYTXHMD' => 68,
        'SYDWJBXX'=>69,

//        'XZQZXX' => 70,
//        'XZZSXX' => 71,
//        'XZCJXX' => 72,
//        'XZQRXX' => 73,
//        'XZJFXX' => 74,
//        'JDJCXX' => 75,
//        'XZJLXX' => 76,
//        'QTXZZFXX' => 77,
        'HEIMDXX' => 78,
        'HONGMDXX' => 79,
        'HYFJFLJG' => 80,

        'QYHYSJ' => 81,
        'DWYSZCXX'=>82,
        'TQMYQYZK'=>83,

        'ZFCGHT'=>84,
        'GGZYJYHT'=>85,
        'GQCGHT'=>86,
        'GCJSHT'=>87,
        'QTHT'=>88,

        'CCJCJG'=>89,
        'XYSFSQ'=>90,

        'XZQZ' => 91,
        'XZZS' => 92,
        'XZCJ' => 93,
        'XZQR' => 94,
        'XZJF' => 95,
        'JDJC' => 96,
        'XZJL' => 97,
        'QTXZZF' => 98,

        //@position_type_99
        'TEST' => 500
    );

    const USERGROUP_TYPE_RELATIONSHIP = array(
        IUserGroup::ID['NULL'] => array(
            self::TYPE['NULL'],
            self::TYPE['XBXZCF'],
            self::TYPE['XBXZXK'],
            self::TYPE['CCJCJG'],
            self::TYPE['XZQZ'],
            self::TYPE['XZZS'],
            self::TYPE['XZCJ'],
            self::TYPE['XZQR'],
            self::TYPE['XZJF'],
            self::TYPE['JDJC'],
            self::TYPE['XZJL'],
            self::TYPE['QTXZZF'],

        ),
        IUserGroup::ID['FGW'] => array(
            self::TYPE['JGJCDXZJL'], 
            self::TYPE['TEST'], 
            self::TYPE['SJJXMXX'], 
            self::TYPE['SYDWJBXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XCZJ'] => array(
            self::TYPE['ZFCGDLJGXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XGAJ'] => array(
            self::TYPE['YSCRJZJJJZGRDXX'],
            self::TYPE['JDCWFXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XSFJ'] => array(
            self::TYPE['SFJDJGCYRYZGXX'],
            self::TYPE['SFJDJGDJXX'],
            self::TYPE['GZJGJBXX'],
            self::TYPE['GZYXX'],
            self::TYPE['JCFLFWSXX'],
            self::TYPE['JCFLFWGZZJBXX'],
            self::TYPE['LSSWSXX'],
            self::TYPE['LSZYZGZXX'],
            self::TYPE['JGRYXXSSFJ'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XNYNCJ'] => array(
            self::TYPE['GJJLTQYRZXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XSLJ'] => array(
            self::TYPE['SLGCZBXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XSTJ'] => array(
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XSWJ'] => array(
            self::TYPE['ESCJDPGJGHZZS'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XRSJ'] => array(
            self::TYPE['ZYJNZSXX'],
            self::TYPE['YLBXXX'],
            self::TYPE['YZTQSBXXHMD'],
            self::TYPE['SYBXXX'],
            self::TYPE['SBQYXX'],
            self::TYPE['GZRYXX'],
            self::TYPE['YZTQNMGGZHMD'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XJTJ'] => array(
            self::TYPE['SLYSXKZXX'], 
            self::TYPE['GRRYXXJTJ'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XMZJ'] => array(
            self::TYPE['SHZZNJXX'],
            self::TYPE['GRRYXXMZJ'],
            self::TYPE['MBFQYML'],
            self::TYPE['SHTTDJXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],

        ),
        IUserGroup::ID['XGXJ'] => array(
            self::TYPE['SJQYJSZXRDXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
            self::TYPE['TQMYQYZK'],
        ),
        IUserGroup::ID['XJYTYJ'] => array(
            self::TYPE['JSZGXX'],
            self::TYPE['SJYXXS'],
            self::TYPE['JYJGXINXI'],
            self::TYPE['GRRYXXJYJ'],
            self::TYPE['JGRYXXSJYJ'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XGLJ'] => array(),
        IUserGroup::ID['XWJW'] => array(
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ']
        ),
        IUserGroup::ID['XZJJ'] => array(
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XWLJ'] => array(
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XCGJ'] => array(
            self::TYPE['XZXKQYXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XSJJ'] => array(
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],

            self::TYPE['QYHYSJ']
        ),
        IUserGroup::ID['XSCJGJ'] => array(
            self::TYPE['QIYEJBXX'],
            self::TYPE['GTGSHXX'],
            self::TYPE['CMQYSBXX'],
            self::TYPE['YPLSQYXX'],
            self::TYPE['JGRYXX'],
            self::TYPE['SXQYHMD'],
            self::TYPE['SPYPTSJBJLGR'],
            self::TYPE['SPYPTSJBJLDW'],
            self::TYPE['HNMPCPXX'],
            self::TYPE['QYYCMLXX'],
            self::TYPE['QYZXXX'],
            self::TYPE['QYDXXX'],
            self::TYPE['CCJCJGXX'],
            self::TYPE['FRXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XYJJ'] => array(
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XXCZXJ'] => array(
        ),
        IUserGroup::ID['XGGZYJYZX'] => array(
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XFGZX'] => array(
            self::TYPE['SPFYSXK'],
            self::TYPE['FDCKFQYZZXX'],
            self::TYPE['JGRYXXSFGJ'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XYBJ'] => array(
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XZRZYJ'] => array(
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XLYJ'] => array(),
        IUserGroup::ID['XQXJ'] => array(),
        IUserGroup::ID['XTJJ'] => array(),
        IUserGroup::ID['XXFJYDD'] => array(),
        IUserGroup::ID['XHYZ'] => array(),
        IUserGroup::ID['XZZZ'] => array(),
        IUserGroup::ID['XYHZ'] => array(),
        IUserGroup::ID['XFJZ'] => array(),
        IUserGroup::ID['XDHZ'] => array(),
        IUserGroup::ID['XWCZ'] => array(),
        IUserGroup::ID['XMJZ'] => array(),
        IUserGroup::ID['XCJX'] => array(),
        IUserGroup::ID['XXJX'] => array(),
        IUserGroup::ID['XCWZ'] => array(),
        IUserGroup::ID['XHGZ'] => array(),
        IUserGroup::ID['XAPZ'] => array(),
        IUserGroup::ID['XXJZZYKFQ'] => array(),
        IUserGroup::ID['XHGCYJJQ'] => array(),
        IUserGroup::ID['XGXZ'] => array(),
        IUserGroup::ID['XCGZ'] => array(),
        IUserGroup::ID['XHLX'] => array(),
        IUserGroup::ID['XPSZ'] => array()
    );

    const STATUS_NORMAL = 0;

    const STATUS_DELETE = -2;
}