<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'FGW' => 1,
        'XCZJ' => 2,
        'XGAJ' => 3,
        'XSFJ' => 4,
        'XNYNCJ' => 5,
        'XSLJ' => 6,
        'XSTJ' => 7,
        'XSWJ' => 8,
        'XRSJ' => 9,
        'XJTJ' => 10,
        'XMZJ' => 11,
        'XGXJ' => 12,
        'XJYTYJ' => 13,
        'XGLJ' => 14,
        'XWJW' => 15,
        'XZJJ' => 16,
        'XWLJ' => 17,
        'XCGJ' => 18,
        'XSJJ' => 19,
        'XSCJGJ' => 20,
        'XYJJ' => 21,
        'XXCZXJ' => 22,
        'XGGZYJYZX' => 23,
        'XFGZX' => 24,
        'XYBJ' => 25,
        'XZRZYJ' => 26,
        'XLYJ' => 27,
        'XQXJ' => 28,
        'XTJJ' => 29,
        'XXFJYDD' => 30,
        'XHYZ' => 31,
        'XZZZ' => 32,
        'XYHZ' => 33,
        'XFJZ' => 34,
        'XDHZ' => 35,
        'XWCZ' => 36,
        'XMJZ' => 37,
        'XCJX' => 38,
        'XXJX' => 39,
        'XCWZ' => 40,
        'XHGZ' => 41,
        'XAPZ' => 42,
        'XXJZZYKFQ' => 43,
        'XHGCYJJQ' => 44,
        'XGXZ' => 45,
        'XCGZ' => 46,
        'XHLX' => 47,
        'XPSZ' => 48,
    );
}
