<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const IDENTIFY = array(
        IUserGroup::ID['NULL'] => 'NULL',
        IUserGroup::ID['FGW'] => 'FGW',
        IUserGroup::ID['XCZJ'] => 'XCZJ',
        IUserGroup::ID['XGAJ'] => 'XGAJ',
        IUserGroup::ID['XSFJ'] => 'XSFJ',
        IUserGroup::ID['XNYNCJ'] => 'XNYNCJ',
        IUserGroup::ID['XSLJ'] => 'XSLJ',
        IUserGroup::ID['XSTJ'] => 'XSTJ',
        IUserGroup::ID['XSWJ'] => 'XSWJ',
        IUserGroup::ID['XRSJ'] => 'XRSJ',
        IUserGroup::ID['XJTJ'] => 'XJTJ',
        IUserGroup::ID['XMZJ'] => 'XMZJ',
        IUserGroup::ID['XGXJ'] => 'XGXJ',
        IUserGroup::ID['XJYTYJ'] => 'XJYTYJ',
        IUserGroup::ID['XGLJ'] => 'XGLJ',
        IUserGroup::ID['XWJW'] => 'XWJW',
        IUserGroup::ID['XZJJ'] => 'XZJJ',
        IUserGroup::ID['XWLJ'] => 'XWLJ',
        IUserGroup::ID['XCGJ'] => 'XCGJ',
        IUserGroup::ID['XSJJ'] => 'XSJJ',
        IUserGroup::ID['XSCJGJ'] => 'XSCJGJ',
        IUserGroup::ID['XYJJ'] => 'XYJJ',
        IUserGroup::ID['XXCZXJ'] => 'XXCZXJ',
        IUserGroup::ID['XGGZYJYZX'] => 'XGGZYJYZX',
        IUserGroup::ID['XFGZX'] => 'XFGZX',
        IUserGroup::ID['XYBJ'] => 'XYBJ',
        IUserGroup::ID['XZRZYJ'] => 'XZRZYJ',
        IUserGroup::ID['XLYJ'] => 'XLYJ',
        IUserGroup::ID['XQXJ'] => 'XQXJ',
        IUserGroup::ID['XTJJ'] => 'XTJJ',
        IUserGroup::ID['XXFJYDD'] => 'XXFJYDD',
        IUserGroup::ID['XHYZ'] => 'XHYZ',
        IUserGroup::ID['XZZZ'] => 'XZZZ',
        IUserGroup::ID['XYHZ'] => 'XYHZ',
        IUserGroup::ID['XFJZ'] => 'XFJZ',
        IUserGroup::ID['XDHZ'] => 'XDHZ',
        IUserGroup::ID['XWCZ'] => 'XWCZ',
        IUserGroup::ID['XMJZ'] => 'XMJZ',
        IUserGroup::ID['XCJX'] => 'XCJX',
        IUserGroup::ID['XXJX'] => 'XXJX',
        IUserGroup::ID['XCWZ'] => 'XCWZ',
        IUserGroup::ID['XHGZ'] => 'XHGZ',
        IUserGroup::ID['XAPZ'] => 'XAPZ',
        IUserGroup::ID['XXJZZYKFQ'] => 'XXJZZYKFQ',
        IUserGroup::ID['XHGCYJJQ'] => 'XHGCYJJQ',
        IUserGroup::ID['XGXZ'] => 'XGXZ',
        IUserGroup::ID['XCGZ'] => 'XCGZ',
        IUserGroup::ID['XHLX'] => 'XHLX',
        IUserGroup::ID['XPSZ'] => 'XPSZ',
    );
}
